// This file is auto-generated by @hey-api/openapi-ts

/**
 * AdminActivityPoint
 */
export type AdminActivityPoint = {
    /**
     * Day
     */
    day: string;
    /**
     * Posts
     */
    posts: number;
    /**
     * Votes
     */
    votes: number;
};

/**
 * AdminFlagItem
 */
export type AdminFlagItem = {
    /**
     * Id
     */
    id: string;
    /**
     * Content
     */
    content: string;
    /**
     * Created By Name
     */
    created_by_name: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Parent Id
     */
    parent_id: string | null;
    /**
     * Hidden
     */
    hidden: boolean;
    /**
     * Upvotes
     */
    upvotes: number;
    /**
     * Downvotes
     */
    downvotes: number;
    /**
     * Reports
     */
    reports: Array<AdminFlagReport>;
};

/**
 * AdminFlagReport
 */
export type AdminFlagReport = {
    /**
     * Reporter
     */
    reporter: string;
    /**
     * Notice
     */
    notice: string | null;
};

/**
 * AdminLogin
 */
export type AdminLogin = {
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
};

/**
 * AdminPostItem
 */
export type AdminPostItem = {
    /**
     * Id
     */
    id: string;
    /**
     * Content
     */
    content: string;
    /**
     * Created By Name
     */
    created_by_name: string;
    /**
     * Created By Id
     */
    created_by_id: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Parent Id
     */
    parent_id: string | null;
    /**
     * Hidden
     */
    hidden: boolean;
    /**
     * Upvotes
     */
    upvotes: number;
    /**
     * Downvotes
     */
    downvotes: number;
    /**
     * Flag Count
     */
    flag_count: number;
};

/**
 * AdminStats
 */
export type AdminStats = {
    /**
     * Total Users
     */
    total_users: number;
    /**
     * Total Posts
     */
    total_posts: number;
    /**
     * Total Replies
     */
    total_replies: number;
    /**
     * Total Votes
     */
    total_votes: number;
    /**
     * Active Flags
     */
    active_flags: number;
    /**
     * Hidden Posts
     */
    hidden_posts: number;
    /**
     * Banned Users
     */
    banned_users: number;
    /**
     * Activity
     */
    activity: Array<AdminActivityPoint>;
    /**
     * Top Posters
     */
    top_posters: Array<AdminTopPoster>;
    /**
     * Top Posts
     */
    top_posts: Array<AdminTopPost>;
};

/**
 * AdminTopPost
 */
export type AdminTopPost = {
    /**
     * Id
     */
    id: string;
    /**
     * Content
     */
    content: string;
    /**
     * Created By Name
     */
    created_by_name: string;
    /**
     * Score
     */
    score: number;
};

/**
 * AdminTopPoster
 */
export type AdminTopPoster = {
    /**
     * Name
     */
    name: string;
    /**
     * Post Count
     */
    post_count: number;
};

/**
 * AdminUserItem
 */
export type AdminUserItem = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    ban_mode: BanMode;
    /**
     * Is Moderator
     */
    is_moderator: boolean;
    subscription_mode: SubscriptionMode;
    /**
     * Post Count
     */
    post_count: number;
    /**
     * Flags Received
     */
    flags_received: number;
};

/**
 * BanData
 */
export type BanData = {
    mode: BanMode;
};

/**
 * BanMode
 */
export type BanMode = 'none' | 'blocked' | 'blocked_hidden' | 'shadow';

/**
 * FlagData
 */
export type FlagData = {
    /**
     * Post
     */
    post: string;
    /**
     * Notice
     */
    notice: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * ModeratorData
 */
export type ModeratorData = {
    /**
     * Is Moderator
     */
    is_moderator: boolean;
};

/**
 * Post
 */
export type Post = {
    /**
     * Id
     */
    id?: string;
    /**
     * Created At
     */
    created_at?: string;
    /**
     * Created By Id
     */
    created_by_id?: string | null;
    /**
     * Parent Id
     */
    parent_id?: string | null;
    /**
     * Content
     */
    content: string;
    /**
     * Hidden
     */
    hidden?: boolean;
    /**
     * Created By Name
     */
    readonly created_by_name: string;
    /**
     * Upvotes
     */
    readonly upvotes: number;
    /**
     * Downvotes
     */
    readonly downvotes: number;
    /**
     * Children Count
     */
    readonly children_count: number;
};

/**
 * PostCreate
 */
export type PostCreate = {
    /**
     * Parent
     */
    parent?: string | null;
    /**
     * Content
     */
    content: string;
};

/**
 * PostWithChildren
 */
export type PostWithChildren = {
    /**
     * Id
     */
    id: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Content
     */
    content: string;
    /**
     * Parent Id
     */
    parent_id: string | null;
    /**
     * Created By Name
     */
    created_by_name: string;
    /**
     * Upvotes
     */
    upvotes: number;
    /**
     * Downvotes
     */
    downvotes: number;
    /**
     * Children Count
     */
    children_count: number;
    /**
     * Children
     */
    children?: Array<PostWithChildren>;
};

/**
 * SessionInfo
 */
export type SessionInfo = {
    /**
     * Role
     */
    role: 'admin' | 'moderator';
};

/**
 * SessionInit
 */
export type SessionInit = {
    /**
     * Username
     */
    username: string;
};

/**
 * SubscribeData
 */
export type SubscribeData = {
    /**
     * Subscription
     */
    subscription: string;
    mode: SubscriptionMode;
};

/**
 * SubscriptionMode
 */
export type SubscriptionMode = 'none' | 'user' | 'all' | 'global';

/**
 * UserPublic
 * Session payload. Deliberately omits `ban_mode` (a shadow-banned user must
 * not learn they're banned) and the raw push `subscription`.
 */
export type UserPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Is Moderator
     */
    is_moderator: boolean;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

/**
 * Vote
 */
export type Vote = {
    /**
     * Id
     */
    id?: string;
    /**
     * Value
     */
    value: number;
    /**
     * Post Id
     */
    post_id?: string | null;
    /**
     * Created By Id
     */
    created_by_id?: string | null;
};

/**
 * VoteData
 */
export type VoteData = {
    /**
     * Post
     */
    post: string;
    /**
     * Value
     */
    value: -1 | 0 | 1;
};

export type GetPostApiV1PostsInfoPostIdGetData = {
    body?: never;
    path: {
        /**
         * Post Id
         */
        post_id: string;
    };
    query?: never;
    url: '/api/v1/posts/info/{post_id}';
};

export type GetPostApiV1PostsInfoPostIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetPostApiV1PostsInfoPostIdGetError = GetPostApiV1PostsInfoPostIdGetErrors[keyof GetPostApiV1PostsInfoPostIdGetErrors];

export type GetPostApiV1PostsInfoPostIdGetResponses = {
    /**
     * Successful Response
     */
    200: PostWithChildren;
};

export type GetPostApiV1PostsInfoPostIdGetResponse = GetPostApiV1PostsInfoPostIdGetResponses[keyof GetPostApiV1PostsInfoPostIdGetResponses];

export type GetPostsApiV1PostsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Since
         */
        since?: string | null;
        /**
         * Max Hours
         */
        max_hours?: number;
        /**
         * Limit
         */
        limit?: number;
        /**
         * Order
         */
        order?: 'votes' | 'newest';
    };
    url: '/api/v1/posts/';
};

export type GetPostsApiV1PostsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetPostsApiV1PostsGetError = GetPostsApiV1PostsGetErrors[keyof GetPostsApiV1PostsGetErrors];

export type GetPostsApiV1PostsGetResponses = {
    /**
     * Response Get Posts Api V1 Posts  Get
     * Successful Response
     */
    200: Array<Post>;
};

export type GetPostsApiV1PostsGetResponse = GetPostsApiV1PostsGetResponses[keyof GetPostsApiV1PostsGetResponses];

export type CreatePostApiV1PostsPostData = {
    body: PostCreate;
    path?: never;
    query?: never;
    url: '/api/v1/posts/';
};

export type CreatePostApiV1PostsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreatePostApiV1PostsPostError = CreatePostApiV1PostsPostErrors[keyof CreatePostApiV1PostsPostErrors];

export type CreatePostApiV1PostsPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type VoteApiV1PostsVotePostData = {
    body: VoteData;
    path?: never;
    query?: never;
    url: '/api/v1/posts/vote';
};

export type VoteApiV1PostsVotePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type VoteApiV1PostsVotePostError = VoteApiV1PostsVotePostErrors[keyof VoteApiV1PostsVotePostErrors];

export type VoteApiV1PostsVotePostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetVotesApiV1PostsVotesGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/posts/votes';
};

export type GetVotesApiV1PostsVotesGetResponses = {
    /**
     * Response Get Votes Api V1 Posts Votes Get
     * Successful Response
     */
    200: Array<Vote>;
};

export type GetVotesApiV1PostsVotesGetResponse = GetVotesApiV1PostsVotesGetResponses[keyof GetVotesApiV1PostsVotesGetResponses];

export type FlagApiV1PostsFlagPostData = {
    body: FlagData;
    path?: never;
    query?: never;
    url: '/api/v1/posts/flag';
};

export type FlagApiV1PostsFlagPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type FlagApiV1PostsFlagPostError = FlagApiV1PostsFlagPostErrors[keyof FlagApiV1PostsFlagPostErrors];

export type FlagApiV1PostsFlagPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetSessionApiV1UserGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/user/';
};

export type GetSessionApiV1UserGetResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type GetSessionApiV1UserGetResponse = GetSessionApiV1UserGetResponses[keyof GetSessionApiV1UserGetResponses];

export type InitSessionApiV1UserPostData = {
    body: SessionInit;
    path?: never;
    query?: never;
    url: '/api/v1/user/';
};

export type InitSessionApiV1UserPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type InitSessionApiV1UserPostError = InitSessionApiV1UserPostErrors[keyof InitSessionApiV1UserPostErrors];

export type InitSessionApiV1UserPostResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type InitSessionApiV1UserPostResponse = InitSessionApiV1UserPostResponses[keyof InitSessionApiV1UserPostResponses];

export type GetVapidPublicKeyApiV1NotifyVapidPublicKeyGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/notify/vapid_public_key';
};

export type GetVapidPublicKeyApiV1NotifyVapidPublicKeyGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type SubscribeApiV1NotifySubscribePostData = {
    body: SubscribeData;
    path?: never;
    query?: never;
    url: '/api/v1/notify/subscribe';
};

export type SubscribeApiV1NotifySubscribePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SubscribeApiV1NotifySubscribePostError = SubscribeApiV1NotifySubscribePostErrors[keyof SubscribeApiV1NotifySubscribePostErrors];

export type SubscribeApiV1NotifySubscribePostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type AdminLoginApiV1AdminLoginPostData = {
    body: AdminLogin;
    path?: never;
    query?: never;
    url: '/api/v1/admin/login';
};

export type AdminLoginApiV1AdminLoginPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AdminLoginApiV1AdminLoginPostError = AdminLoginApiV1AdminLoginPostErrors[keyof AdminLoginApiV1AdminLoginPostErrors];

export type AdminLoginApiV1AdminLoginPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type AdminLogoutApiV1AdminLogoutPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/admin/logout';
};

export type AdminLogoutApiV1AdminLogoutPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type AdminSessionApiV1AdminSessionGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/admin/session';
};

export type AdminSessionApiV1AdminSessionGetResponses = {
    /**
     * Successful Response
     */
    200: SessionInfo;
};

export type AdminSessionApiV1AdminSessionGetResponse = AdminSessionApiV1AdminSessionGetResponses[keyof AdminSessionApiV1AdminSessionGetResponses];

export type AdminFlagsApiV1AdminFlagsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/admin/flags';
};

export type AdminFlagsApiV1AdminFlagsGetResponses = {
    /**
     * Response Admin Flags Api V1 Admin Flags Get
     * Successful Response
     */
    200: Array<AdminFlagItem>;
};

export type AdminFlagsApiV1AdminFlagsGetResponse = AdminFlagsApiV1AdminFlagsGetResponses[keyof AdminFlagsApiV1AdminFlagsGetResponses];

export type AdminDismissFlagsApiV1AdminFlagsPostIdDismissPostData = {
    body?: never;
    path: {
        /**
         * Post Id
         */
        post_id: string;
    };
    query?: never;
    url: '/api/v1/admin/flags/{post_id}/dismiss';
};

export type AdminDismissFlagsApiV1AdminFlagsPostIdDismissPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AdminDismissFlagsApiV1AdminFlagsPostIdDismissPostError = AdminDismissFlagsApiV1AdminFlagsPostIdDismissPostErrors[keyof AdminDismissFlagsApiV1AdminFlagsPostIdDismissPostErrors];

export type AdminDismissFlagsApiV1AdminFlagsPostIdDismissPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type AdminHidePostApiV1AdminPostsPostIdHidePostData = {
    body?: never;
    path: {
        /**
         * Post Id
         */
        post_id: string;
    };
    query?: never;
    url: '/api/v1/admin/posts/{post_id}/hide';
};

export type AdminHidePostApiV1AdminPostsPostIdHidePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AdminHidePostApiV1AdminPostsPostIdHidePostError = AdminHidePostApiV1AdminPostsPostIdHidePostErrors[keyof AdminHidePostApiV1AdminPostsPostIdHidePostErrors];

export type AdminHidePostApiV1AdminPostsPostIdHidePostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type AdminUnhidePostApiV1AdminPostsPostIdUnhidePostData = {
    body?: never;
    path: {
        /**
         * Post Id
         */
        post_id: string;
    };
    query?: never;
    url: '/api/v1/admin/posts/{post_id}/unhide';
};

export type AdminUnhidePostApiV1AdminPostsPostIdUnhidePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AdminUnhidePostApiV1AdminPostsPostIdUnhidePostError = AdminUnhidePostApiV1AdminPostsPostIdUnhidePostErrors[keyof AdminUnhidePostApiV1AdminPostsPostIdUnhidePostErrors];

export type AdminUnhidePostApiV1AdminPostsPostIdUnhidePostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type AdminDeletePostApiV1AdminPostsPostIdDeleteData = {
    body?: never;
    path: {
        /**
         * Post Id
         */
        post_id: string;
    };
    query?: never;
    url: '/api/v1/admin/posts/{post_id}';
};

export type AdminDeletePostApiV1AdminPostsPostIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AdminDeletePostApiV1AdminPostsPostIdDeleteError = AdminDeletePostApiV1AdminPostsPostIdDeleteErrors[keyof AdminDeletePostApiV1AdminPostsPostIdDeleteErrors];

export type AdminDeletePostApiV1AdminPostsPostIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type AdminUsersApiV1AdminUsersGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Search
         */
        search?: string | null;
    };
    url: '/api/v1/admin/users';
};

export type AdminUsersApiV1AdminUsersGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AdminUsersApiV1AdminUsersGetError = AdminUsersApiV1AdminUsersGetErrors[keyof AdminUsersApiV1AdminUsersGetErrors];

export type AdminUsersApiV1AdminUsersGetResponses = {
    /**
     * Response Admin Users Api V1 Admin Users Get
     * Successful Response
     */
    200: Array<AdminUserItem>;
};

export type AdminUsersApiV1AdminUsersGetResponse = AdminUsersApiV1AdminUsersGetResponses[keyof AdminUsersApiV1AdminUsersGetResponses];

export type AdminBanUserApiV1AdminUsersUserIdBanPostData = {
    body: BanData;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/admin/users/{user_id}/ban';
};

export type AdminBanUserApiV1AdminUsersUserIdBanPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AdminBanUserApiV1AdminUsersUserIdBanPostError = AdminBanUserApiV1AdminUsersUserIdBanPostErrors[keyof AdminBanUserApiV1AdminUsersUserIdBanPostErrors];

export type AdminBanUserApiV1AdminUsersUserIdBanPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type AdminSetModeratorApiV1AdminUsersUserIdModeratorPostData = {
    body: ModeratorData;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/admin/users/{user_id}/moderator';
};

export type AdminSetModeratorApiV1AdminUsersUserIdModeratorPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AdminSetModeratorApiV1AdminUsersUserIdModeratorPostError = AdminSetModeratorApiV1AdminUsersUserIdModeratorPostErrors[keyof AdminSetModeratorApiV1AdminUsersUserIdModeratorPostErrors];

export type AdminSetModeratorApiV1AdminUsersUserIdModeratorPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type AdminPostsApiV1AdminPostsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Limit
         */
        limit?: number;
        /**
         * Offset
         */
        offset?: number;
        /**
         * Include Hidden
         */
        include_hidden?: boolean;
        /**
         * User Id
         */
        user_id?: string | null;
        /**
         * Search
         */
        search?: string | null;
    };
    url: '/api/v1/admin/posts';
};

export type AdminPostsApiV1AdminPostsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AdminPostsApiV1AdminPostsGetError = AdminPostsApiV1AdminPostsGetErrors[keyof AdminPostsApiV1AdminPostsGetErrors];

export type AdminPostsApiV1AdminPostsGetResponses = {
    /**
     * Response Admin Posts Api V1 Admin Posts Get
     * Successful Response
     */
    200: Array<AdminPostItem>;
};

export type AdminPostsApiV1AdminPostsGetResponse = AdminPostsApiV1AdminPostsGetResponses[keyof AdminPostsApiV1AdminPostsGetResponses];

export type AdminStatsApiV1AdminStatsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/admin/stats';
};

export type AdminStatsApiV1AdminStatsGetResponses = {
    /**
     * Successful Response
     */
    200: AdminStats;
};

export type AdminStatsApiV1AdminStatsGetResponse = AdminStatsApiV1AdminStatsGetResponses[keyof AdminStatsApiV1AdminStatsGetResponses];

export type IndexGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type IndexGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};